compounds = ['according to', 'air conditioning', 'air force', 'alarm clock',
'all right', 'bank account', 'because of', 'board game', 'bus station',
'bus stop', 'capital letter', 'car park', 'carbon dioxide', 'carbon footprint',
'carbon monoxide', 'CD player', 'cd player', 'central heating', 'chat show', 'check-in counter',
'check-in desk', 'chest of drawers', 'chewing gum', 'classical music',
'climate change', 'common sense', 'credit card', 'de facto', 'debit card',
'definite article', 'department store', 'digital camera', 'dining room',
'disc jockey', 'disk jockey', 'driver’s license', 'driving licence', 'each other',
'environmentally friendly', 'exchange rate', 'exclamation mark', 'extreme sports',
'face to face', 'fast food', 'fed up', 'fire brigade', 'fire station', 'first floor',
'first lady', 'first language', 'first name', 'first person', 'frying pan',
'full stop', 'global warming', 'good afternoon', 'good morning', 'good night',
'grocery store', 'ground floor', 'hard drive', 'have to', 'health care',
'heart attack', 'high school', 'hip hop', 'human rights', 'ice cream', 'ice hockey',
'ice skating', 'ID card', 'id card', 'identity card', 'indefinite article', 'instead of',
'inverted commas', 'junk food', 'last minute', 'last name', 'living room', 'main course',
'martial art', 'message board', 'mineral water', 'mixing bowl', 'mobile phone',
'modal verb', 'MP3 player', 'mp3 player', 'native speaker', 'navy blue', 'net surfer',
'next door', 'next to', 'no one', 'olive oil', 'on to', 'ought to', 'out of',
'owing to', 'pen friend', 'per cent', 'petrol station', 'phrasal verb', 'pocket money',
'point of view', 'polar bear', 'police officer', 'police station', 'post office',
'primary school', 'prime minister', 'public transport', 'question mark',
'real estate', 'remote control', 'rush hour', 'science fiction', 'second person',
'secondary school', 'shop assistant', 'sitting room', 'soap opera', 'social networking',
'soft drink', 'sports center', 'sports centre', 'steering wheel', 'stock market',
'swimming costume', 'swimming pool', 'table tennis', 'text message', 'third person',
'tour guide', 'traffic jam', 'traffic light', 'travel agent', 'upside down', 'used to',
'vice president', 'video clip', 'video game', 'virtual reality', 'washing machine',
'weather forecast', 'web page', 'worn out']

hyphens = ['bad-tempered', 'brand-new', 'brother-in-law', 'CD-ROM', 'cd-rom', 'check-in',
'check-in counter', 'check-in desk', 'daughter-in-law', 'duty-free', 'easy-going',
'e-mail', 'E-mail', 'face-to-face', 'father-in-law', 'film-maker', 'first-floor',
'full-time', 'good-looking', 'grown-up', 'half-price', 'hand-held', 'hard-working',
'heart-warming', 'high-tech', 'hip-hop', 'hi-tech', 'last-minute', 'left-hand',
'long-distance', 'long-term', 'make-up', 'middle-aged', 'mother-in-law', 'next-door',
'non-smoking', 'old-fashioned', 'out-of-date', 'part-time', 'right-hand', 'second-hand',
'self-confidence', 'self-confident', 'self-service', 'semi-final', 'short-term',
'sister-in-law', 'so-called', 'son-in-law', 'take-off', 'tee-shirt', 'T-shirt', 't-shirt',
'up-to-date', 'washing-up', 'well-balanced', 'well-built', 'well-dressed', 'well-known',
'well-organised', 'well-organized', 'well-paid', 'worn-out', 'X-ray', 'x-ray']

plurals = ['CD-ROMs', 'cd-roms', 'check-ins', 'check-in counters', 'check-in desks',
'e-mails', 'E-mails', 'film-makers', 'grown-ups', 'semi-finals', 'take-offs', 'tee-shirts',
'T-shirts', 't-shirts', 'X-rays', 'air forces', 'alarm clocks', 'bank accounts', 'board games',
'bus stations', 'bus stops', 'capital letters', 'car parks', 'carbon footprints',
'CD players', 'cd players', 'chat shows', 'check-in counters', 'check-in desks', 'credit cards',
'debit cards', 'definite articles', 'department stores', 'digital cameras',
'dining rooms', 'disc jockeys', 'disk jockeys', 'driving licences',
'exchange rates', 'exclamation marks', 'fire brigades', 'fire stations',
'first floors', 'first languages', 'first names', 'frying pans', 'full stops',
'grocery stores', 'ground floors', 'hard drives', 'heart attacks', 'high schools',
'ice creams', 'ID cards', 'id cards', 'identity cards', 'indefinite articles', 'last names',
'living rooms', 'main courses', 'martial arts', 'message boards', 'mineral waters',
'mixing bowls', 'mobile phones', 'modal verbs', 'MP3 players', 'mp3 players', 'native speakers',
'net surfers', 'olive oils', 'pen friends', 'petrol stations', 'phrasal verbs',
'polar bears', 'police officers', 'police stations', 'post offices', 'primary schools',
'prime ministers', 'question marks', 'remote controls', 'rush hours', 'secondary schools',
'shop assistants', 'sitting rooms', 'soap operas', 'soft drinks', 'sports centers',
'sports centres', 'steering wheels', 'stock markets', 'swimming costumes', 'swimming pools',
'text messages', 'tour guides', 'traffic jams', 'traffic lights', 'travel agents', 'vice presidents',
'video clips', 'video games', 'washing machines', 'weather forecasts', 'web pages']
